### ISSUE TITLE
Can you please provide a way to download translations from multiple projects ? 

### ISSUE THREAD

**Issue by shehramjamil** [hyperdevs-team/poeditor-android-gradle-plugin#43]
I have been working on a project with 20000 lines of stings. I am deciding to split them up into small projects for better management. 

Can you please update the PoEditorStringsImporter.kt for handling a list of project IDs in order to get translations from multiple projects.

**Comment by adriangl** [comment]
Hello @shehramjamil! Thanks for reaching us!

We've been evaluating the complexity of doing this and add it to the plugin, but it's a complex development. It would imply:
* Downloading strings for each project (and that would most likely require multiple API keys handling)
* Ensuring that the languages of each project are set-up properly. I don't know how you would do the split, but there would be many possible split strategies: dividing by language, by terms... And the plug-in should support and work correctly in all cases
* Combining all the XMLs for the same language in each project, also making sure that no string key collisions happen because of having the same string in multiple projects (or adding some kind of collision control for such cases)

Also, I'm not quite sure if we should do it since it would be a way to circumvent the 1000 strings limit in free accounts, and I don't know if that would break any clause of the PoEditor ToS.

All in all, currently we don't have much time to tackle such development (apart from the possible legal issues that might arise) so for now we won't be able to do it. However, the project is open source, so if you feel like it you can do a PR with the changes, just check if this development could break PoEditor ToS or not before doing it.
